template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|-@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '@(requirements|.github)/**']

  - labels: ['C: source']
    patterns: ['**/*.py|-tests']

  - labels: ['C: docs']
    patterns: ['**/*.md|docs/**']

  - labels: ['C: tests']
    patterns: ['tests/**']

  - labels: ['C: plugins']
    patterns: ['rr_modules/**|rr_plugin.py']

  - labels: ['C: edit']
    patterns: ['rr_edit.py']

  - labels: ['C: notify']
    patterns: ['rr_notify.py']

  - labels: ['C: replacer']
    patterns: ['rr_replacer.py']

  - labels: ['C: sequencer']
    patterns: ['rr_sequencer.py']

  - labels: ['C: upgrade']
    patterns: ['rr_upgrade.py']

  - labels: ['C: settings']
    patterns: ['*.sublime-@(keymap|menu|settings|commands)']

# Label management

labels:
- name: 'C: plugins'
  renamed: plugins
  color: subcategory
  description: Related to plugins.

- name: 'C: edit'
  renamed: edit
  color: subcategory
  description: Related to the edit library.

- name: 'C: notify'
  renamed: notify
  color: subcategory
  description: Related to the notify library.

- name: 'C: replacer'
  renamed: replacer
  color: subcategory
  description: Related to the replacer library.

- name: 'C: sequencer'
  renamed: sequencer
  color: subcategory
  description: Related to the sequencer library.

- name: 'C: upgrade'
  renamed: upgrade
  color: subcategory
  description: Related to upgrade library.

- name: 'C: settings'
  renamed: settings
  color: subcategory
  description: Related to Sublime settings files.
