template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|-@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '@(requirements|.github)/**']

  - labels: [source]
    patterns: ['**/*.py|-tests']

  - labels: [docs]
    patterns: ['**/*.md|docs/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [plugins]
    patterns: ['rr_modules/**|rr_plugin.py']

  - labels: [edit]
    patterns: ['rr_edit.py']

  - labels: [notify]
    patterns: ['rr_notify.py']

  - labels: [replacer]
    patterns: ['rr_replacer.py']

  - labels: [sequencer]
    patterns: ['rr_sequencer.py']

  - labels: [upgrade]
    patterns: ['rr_upgrade.py']

  - labels: [settings]
    patterns: ['*.sublime-@(keymap|menu|settings|commands)']

# Label management

labels:
- name: plugins
  color: subcategory
  description: Related to plugins.

- name: edit
  color: subcategory
  description: Related to the edit library.

- name: notify
  color: subcategory
  description: Related to the notify library.

- name: replacer
  color: subcategory
  description: Related to the replacer library.

- name: sequencer
  color: subcategory
  description: Related to the sequencer library.

- name: upgrade
  color: subcategory
  description: Related to upgrade library.

- name: settings
  color: subcategory
  description: Related to Sublime settings files.
